current: simple

simple:
  overwrite: yes
  length: 2
  table: './codons/simple.csv'
  bases:
    - [A, NR1, First]
    - [B, NR2, Second]
    - [C, NR3, Third]
    - [D, NR4, Fourth]
  pairings:
    - [A, D]
    - [B, C]
  amino-acids:
    - [AM1, Amino 1]
    - [AM2, Amino 2]
    - [AM3, Amino 3]
    - [AM4, Amino 4]
    - [AM5, Amino 5]
    - [AM6, Amino 6]
    - [AM7, Amino 7]
    - [AM8, Amino 8]

default:
  overwrite: no
  bases:
    - [A, Adenina]
    - [C, Cytozyna]
    - [G, Guanina]
    - [T, Tymina]
  rules:
    - [A, T]
    - [C, G]
  amino-acids:
    - [GLY ,  Glycine]
    - [GLA ,  Glutamic acid]
    - [ASA ,  Aspartic acid]
    - [ALA ,  Alanine]
    - [VAL ,  Valine]
    - [ARG ,  Arginine]
    - [SER ,  Serine]
    - [LYS ,  Lysine]
    - [ASP ,  Asparagine]
    - [THR ,  Threonine]
    - [MET ,  Methionine]
    - [ISO ,  Isoleucine]
    - [GLU ,  Glutaminie]
    - [HIS ,  Histidine]
    - [PRO ,  Proline]
    - [LEU ,  Leucine]
    - [TRY ,  Tryptophan]
    - [CYS ,  Cysteine]
    - [TYR ,  Tyrosine]
    - [PHE ,  Phenylalanine]
    - [STOP,  Stop]
  table: ./codons/default.csv
  length: 3

niko:
  overwrite: no
  bases:
    - [A, Adenina]
    - [C, Cytozyna]
    - [G, Guanina]
    - [T, Tymina]
  rules:
    - [A, T]
    - [C, G]
  amino-acids:
    - [START,  Start]
    - [NOP  ,  Nophragine]
    - [NUL  ,  Nulysine]
    - [INC  ,  Inculine]
    - [DEC  ,  Declanine]
    - [SPC  ,  Spicyrosine]
    - [ADD  ,  Addysine]
    - [MUL  ,  Mulithreonine]
    - [CHK  ,  Checkrosine]
    - [FNC  ,  Funcysteine]
    - [ACT  ,  Actyglycine]
    - [STOP ,  Stop]
  table: ./codons/niko.csv
  length: 3

random:
  overwrite: yes
  bases:
    - [A, Z]
    - [B, Y]
  amino-acids:
    - [START,  Start]
    - [NOP  ,  Nophragine]
    - [NUL  ,  Nulysine]
    - [INC  ,  Inculine]
    - [DEC  ,  Declanine]
    - [SPC  ,  Spicyrosine]
    - [ADD  ,  Addysine]
    - [MUL  ,  Mulithreonine]
    - [CHK  ,  Checkrosine]
    - [FNC  ,  Funcysteine]
    - [ACT  ,  Actyglycine]
    - [STOP ,  Stop]
  table: ./codons/random.csv
  length: 2