current: niko

default:
  overwrite: no
  bases:
    - [A, T]
    - [C, G]
  amino-acids:
    - [GLY ,  Glycine]
    - [GLA ,  Glutamic acid]
    - [ASA ,  Aspartic acid]
    - [ALA ,  Alanine]
    - [VAL ,  Valine]
    - [ARG ,  Arginine]
    - [SER ,  Serine]
    - [LYS ,  Lysine]
    - [ASP ,  Asparagine]
    - [THR ,  Threonine]
    - [MET ,  Methionine]
    - [ISO ,  Isoleucine]
    - [GLU ,  Glutaminie]
    - [HIS ,  Histidine]
    - [PRO ,  Proline]
    - [LEU ,  Leucine]
    - [TRY ,  Tryptophan]
    - [CYS ,  Cysteine]
    - [TYR ,  Tyrosine]
    - [PHE ,  Phenylalanine]
    - [STOP,  Stop]
  table: ./codons/default.csv
  length: 3

niko:
  overwrite: no
  bases:
    - [A, T]
    - [C, G]
  amino-acids:
    - [START,  Start]
    - [NOP  ,  Nophragine]
    - [NUL  ,  Nulysine]
    - [INC  ,  Inculine]
    - [DEC  ,  Declanine]
    - [SPC  ,  Spicyrosine]
    - [ADD  ,  Addysine]
    - [MUL  ,  Mulithreonine]
    - [CHK  ,  Checkrosine]
    - [FNC  ,  Funcysteine]
    - [ACT  ,  Actyglycine]
    - [STOP ,  Stop]
  table: ./codons/niko.csv
  length: 3

random:
  overwrite: yes
  bases:
    - [A, Z]
    - [B, Y]
  amino-acids:
    - [START,  Start]
    - [NOP  ,  Nophragine]
    - [NUL  ,  Nulysine]
    - [INC  ,  Inculine]
    - [DEC  ,  Declanine]
    - [SPC  ,  Spicyrosine]
    - [ADD  ,  Addysine]
    - [MUL  ,  Mulithreonine]
    - [CHK  ,  Checkrosine]
    - [FNC  ,  Funcysteine]
    - [ACT  ,  Actyglycine]
    - [STOP ,  Stop]
  table: ./codons/random.csv
  length: 2